#include<stdio.h>
int main()
{
	int c, m, i, j;

	for (i = 0, m = 1 << 5 | 1; c = "MAjAN9KBkBM9JCkDK9ICkFJ9HDkFJ9HDlFI9GDmGH9FEmGH9FElIG9DGlIG9EFlJF9EFpFF9DGpFF9DGpGE9DGpGE9DGpGE9CHoHE9CHoHE9CInID9CInID9CKjKD9CMgLD9CMfMD9CMfMD9DPaND9DRWNE9DSUPD9DURQD9DVQPE9DRTQE9DRTQE9DRSRE9DSRRE9DSAAPQF9ERABKABRF9ERBAKAASF9ESABIUG9FUIUG9FBCPHPBDG9FBCQGODCG9FCDOGNEBH9FBFMGNP9NCHBGLR9iDACEBO9iADAX9iAd9OARAd9JA29JAAAAAhAO9HCAAAAfAAAO9JAAAAAAAAAYAAAABN9JAAEAABBRABAAAABN9JAAEAABBABBBJBABAAAAO9LAACAIABCBBBABABAAAAO9LAACAIABCBBHAAAAO9NCAMBBAIAAAAO9PAAAAKACACAEAAAAO9PAAMAGAEABP9PAAIACAGBDAAQ9PAAABABCACACACBADBP9RABABCACACACBADBP9UABCABCBBBABDAQ9UABCABCBBBABDAQ9YBABCBBBAADBQ9PAHBABCBBAGAR9PAHBBACBABGAR9PAIABACBABFBR9OBIABACABAGBR9OBIAFABAHAR9OCRAHAR9OCbAR9OCOAKAR9ODNAJBR9PCXCR9PCXCR9PCXCR9PCXBS9QCIAMCR9QCIALDR9QEAAEALDR9RDAAEAFAECS9RAABAAEAFADDS9RAAEDBEBCCT9TEAABCAABBAAACT9TEAABEBBAAACT9TEAABEBBAET9RABFBFABADU9RABGAFADAAV9RACFAFADX9XAABAFADX9XAAEBBACY9bAABBBAAb9bAABBAe9"
	                                [(!(c - 57) ? (m = 1 << 5,
	                                        printf("\n")) : (m ^= 1)),
	                                 i++];) {
		for (j = 0; (c - 57) &&
		        (j++ -c - (c < 64 ? 5 : (c > 90 ? -70 : -64)));
		        printf("%c", m));
	}
	return 0;
}
